# Generated by Django 4.2.19 on 2025-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="cgpa",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="end_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="start_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
