# Generated by Django 4.2.19 on 2025-08-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0002_resume_cgpa_resume_end_year_resume_start_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="end_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="start_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
