# Generated by Django 4.2.19 on 2025-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0003_alter_resume_end_year_alter_resume_start_year"),
    ]

    operations = [
        migrations.RemoveField(model_name="resume", name="experience",),
        migrations.AddField(
            model_name="resume",
            name="company_four",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume",
            name="company_one",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume",
            name="company_three",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume",
            name="company_two",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume", name="job_four", field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume", name="job_one", field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume",
            name="job_three",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume", name="job_two", field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume",
            name="role_four",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume", name="role_one", field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume",
            name="role_three",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="resume", name="role_two", field=models.TextField(default="N/A"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=models.TextField(default="N/A"),
        ),
    ]
