# Generated by Django 4.2.19 on 2025-08-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0004_remove_resume_experience_resume_company_four_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="company_four",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="company_one",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="company_three",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="company_two",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_four",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_one",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_three",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_two",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="role_four",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="role_one",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="role_three",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="role_two",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
    ]
