# Generated by Django 4.2.19 on 2025-08-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0005_alter_resume_company_four_alter_resume_company_one_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="resume", name="company_four",),
        migrations.RemoveField(model_name="resume", name="company_one",),
        migrations.RemoveField(model_name="resume", name="company_three",),
        migrations.RemoveField(model_name="resume", name="company_two",),
        migrations.RemoveField(model_name="resume", name="job_four",),
        migrations.RemoveField(model_name="resume", name="job_one",),
        migrations.RemoveField(model_name="resume", name="job_three",),
        migrations.RemoveField(model_name="resume", name="job_two",),
        migrations.RemoveField(model_name="resume", name="role_four",),
        migrations.RemoveField(model_name="resume", name="role_one",),
        migrations.RemoveField(model_name="resume", name="role_three",),
        migrations.RemoveField(model_name="resume", name="role_two",),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.TextField(blank=True, default="N/A", null=True)),
                ("role", models.TextField(blank=True, default="N/A", null=True)),
                ("job", models.TextField(blank=True, default="N/A", null=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="basics.resume",
                    ),
                ),
            ],
        ),
    ]
