# Generated by Django 4.2.19 on 2025-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "basics",
            "0006_remove_resume_company_four_remove_resume_company_one_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="company_one",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="company_two",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="job_one",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="job_two",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="role_one",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="role_two",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(name="Experience",),
    ]
