# Generated by Django 4.2.19 on 2025-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "basics",
            "0007_resume_company_one_resume_company_two_resume_job_one_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="language",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="softskills",
            field=models.TextField(default="Not Specified"),
            preserve_default=False,
        ),
    ]
